"""Validate the post-development weekly residual-momentum hypothesis.

The sign was generated by the development-only failure of the pre-registered
residual-reversal study.  Consequently, development statistics here are only
descriptive; the fixed 2024+ temporal split is the first locked test of this
exact direction, and it is still retrospective rather than prospective OOS.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
PROTOCOL_PATH = SCRIPT_DIR / "weekly_residual_momentum_protocol_2026-08-12.json"
OUTPUT_DIR = SCRIPT_DIR / "_output" / "weekly_residual_momentum"
REPORT_PATH = SCRIPT_DIR / "WEEKLY_RESIDUAL_MOMENTUM_2026-08-12.md"

CORE_SPEC = importlib.util.spec_from_file_location(
    "weekly_residual_reversal_core", SCRIPT_DIR / "weekly_residual_reversal.py"
)
assert CORE_SPEC and CORE_SPEC.loader
core = importlib.util.module_from_spec(CORE_SPEC)
CORE_SPEC.loader.exec_module(core)


def sha256_file(path: Path) -> str:
    """Return a streaming SHA256 digest."""

    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _resolve(locator: str) -> Path:
    path = Path(locator).expanduser()
    return path if path.is_absolute() else REPO_ROOT / path


def load_and_verify_protocol() -> dict[str, Any]:
    """Load the protocol and bind the source data plus genesis audit."""

    protocol = json.loads(PROTOCOL_PATH.read_text(encoding="utf-8"))
    if protocol.get("schema") != "weekly_residual_momentum_protocol_v1":
        raise RuntimeError("unexpected residual-momentum protocol schema")
    if protocol.get("live_trading_authorized") is not False:
        raise RuntimeError("retrospective protocol must not authorize live trading")
    for name in ("ranked_surface", "price_panel", "genesis_audit"):
        record = protocol["inputs"][name]
        actual = sha256_file(_resolve(record["path"]))
        if actual != record["sha256"]:
            raise RuntimeError(f"frozen input drift: {name} expected={record['sha256']} actual={actual}")
    genesis = json.loads(_resolve(protocol["inputs"]["genesis_audit"]["path"]).read_text(encoding="utf-8"))
    observed = genesis["development"]["summary_40bps"]
    if not np.isclose(observed["active_mean"], -0.005680251324765568, rtol=0, atol=1e-15):
        raise RuntimeError("momentum genesis effect drift")
    return protocol


def rank_momentum_signal(surface: pd.DataFrame) -> pd.DataFrame:
    """Use the identical neutralization but rank the positive residual first."""

    neutralized = core.rank_reversal_signal(surface)
    rows = []
    for _, week in neutralized.groupby("decision_dt", sort=True, observed=True):
        week = week.sort_values(["residual_return_5obs", "symbol"], ascending=[False, True], kind="mergesort").copy()
        week["momentum_rank"] = np.arange(1, len(week) + 1, dtype=np.int64)
        rows.append(week.drop(columns="reversal_rank"))
    return pd.concat(rows, ignore_index=True)


def _jsonable(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_jsonable(item) for item in value]
    if isinstance(value, (np.bool_, bool)):
        return bool(value)
    if isinstance(value, (np.integer, int)):
        return int(value)
    if isinstance(value, (np.floating, float)):
        return None if not np.isfinite(value) else float(value)
    return value


def _pct(value: float | None) -> str:
    return "NA" if value is None or not np.isfinite(value) else f"{value * 100:.3f}%"


def write_report(audit: dict[str, Any]) -> None:
    """Write the locked temporal-validation report."""

    dev = audit["development_descriptive"]["summary_40bps"]
    val = audit["locked_validation"]["summary_40bps"]
    lines = [
        "# 周频行业/规模中性短期动量：锁定时间验证",
        "",
        f"- 状态：**{audit['status']}**",
        f"- 冻结协议：`{PROTOCOL_PATH.name}`",
        "- 起源：方向来自已冻结超跌反转策略在开发期的失败，因此开发期统计只作描述，不能确认。",
        "- 边界：2024+ 是首次锁定检验，但仍属历史时间切分；通过也不能授权实盘。",
        "",
        "## 固定策略",
        "",
        "过去 5 个股票观察日收益经申万一级行业和流通市值中性化后，选择正残差最大的 50 只，",
        "排名 75 内保留；次一市场日开盘进入，固定 5 日开盘持有，主成本买 15bp / 卖 25bp。",
        "",
        "## 开发期描述（禁止确认）",
        "",
        f"- 主动周均：{_pct(dev['active_mean'])}；HAC t={dev['hac']['t_stat']:.3f}；",
        f"  bootstrap q05={_pct(dev['bootstrap']['q05'])}。",
        "",
        "## 锁定验证期（2024+）",
        "",
        f"- 周数：{val['weeks']}；组合扣费周均：{_pct(val['candidate_net_mean'])}；",
        f"  全市场基准：{_pct(val['benchmark_mean'])}。",
        f"- 主动周均：{_pct(val['active_mean'])}；HAC t={val['hac']['t_stat']:.3f}；",
        f"  bootstrap q05={_pct(val['bootstrap']['q05'])}。",
        f"- 两个锁定半段主动均值：{', '.join(_pct(row['active_mean']) for row in val['half_means'])}。",
        f"- 目标槽可观察率：{_pct(val['observable_target_slot_rate'])}；",
        f"  复利最大回撤：{_pct(val['compounded_candidate_max_drawdown'])}。",
        f"- 验证门：**{'PASS' if audit['locked_validation']['gate']['passed'] else 'FAIL'}**；",
        f"  60bp 压力门：**{'PASS' if audit['cost_stress']['passed'] else 'FAIL'}**。",
        "",
        "### 验证门逐项",
        "",
    ]
    for name, passed in audit["locked_validation"]["gate"]["checks"].items():
        lines.append(f"- `{name}`: {'PASS' if passed else 'FAIL'}")
    lines.extend(["", "## 结论", "", audit["conclusion"]])
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    """Run the exact post-development sign on the locked temporal split."""

    protocol = load_and_verify_protocol()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    blind = rank_momentum_signal(core.build_blind_surface(protocol))
    blind.to_parquet(OUTPUT_DIR / protocol["outputs"]["blind_ranked_signal"], index=False)
    memberships = core.build_memberships(blind, rank_column="momentum_rank")
    memberships.to_parquet(OUTPUT_DIR / protocol["outputs"]["memberships"], index=False)
    val_end = pd.Timestamp(protocol["sample"]["validation"][1])
    weekly = core.build_weekly_outcomes(protocol, memberships, end_date=val_end, terminal_liquidation=True)
    weekly.to_parquet(OUTPUT_DIR / protocol["outputs"]["weekly"], index=False)
    dev_start = pd.Timestamp(protocol["sample"]["development"][0])
    dev_end = pd.Timestamp(protocol["sample"]["development"][1])
    val_start = pd.Timestamp(protocol["sample"]["validation"][0])
    dev_summaries = {
        bps: core.summarize_segment(
            weekly,
            protocol,
            dev_start,
            dev_end,
            bps=bps,
            halves=protocol["sample"]["development_halves"],
        )
        for bps in (20, 40, 60)
    }
    val_summaries = {
        bps: core.summarize_segment(
            weekly,
            protocol,
            val_start,
            val_end,
            bps=bps,
            halves=protocol["sample"]["validation_halves"],
        )
        for bps in (20, 40, 60)
    }
    val_gate = core.evaluate_gate(val_summaries[40], protocol)
    stress_checks = {
        "validation_60bps_active_mean_positive": val_summaries[60]["active_mean"] > 0,
        "validation_60bps_bootstrap_q05_positive": val_summaries[60]["bootstrap"]["q05"] > 0,
    }
    stress_gate = {"passed": all(stress_checks.values()), "checks": stress_checks}
    passed = bool(val_gate["passed"] and stress_gate["passed"])
    audit: dict[str, Any] = {
        "study_id": protocol["study_id"],
        "protocol_sha256": sha256_file(PROTOCOL_PATH),
        "blind_signal_rows": int(len(blind)),
        "membership_rows": int(len(memberships)),
        "development_is_confirmatory": False,
        "development_descriptive": {
            "summary_20bps": dev_summaries[20],
            "summary_40bps": dev_summaries[40],
            "summary_60bps": dev_summaries[60],
        },
        "locked_validation": {
            "summary_20bps": val_summaries[20],
            "summary_40bps": val_summaries[40],
            "summary_60bps": val_summaries[60],
            "gate": val_gate,
        },
        "cost_stress": stress_gate,
        "live_trading_authorized": False,
        "status": (
            "RETROSPECTIVE_MOMENTUM_CANDIDATE_DAILY_PATH_AND_FORWARD_TEST_REQUIRED"
            if passed
            else "HYPOTHESIS_FALSIFIED_LOCKED_VALIDATION"
        ),
        "conclusion": (
            "锁定验证和 60bp 成本压力均通过；下一步必须构建严格日频自融资路径，并重新进入独立前向测试。"
            if passed
            else "锁定验证或 60bp 成本压力失败；该精确短期动量策略被否决，不做参数救援。"
        ),
    }
    audit = _jsonable(audit)
    (OUTPUT_DIR / protocol["outputs"]["audit"]).write_text(
        json.dumps(audit, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    write_report(audit)
    print(json.dumps({"status": audit["status"]}, ensure_ascii=False))


if __name__ == "__main__":
    main()
